FROM maven:3.9.6-eclipse-temurin-21-alpine

WORKDIR /app

# Copy backend source code (adjust if backend is in subfolder)
COPY backend/ ./backend/

WORKDIR /app/backend

RUN mvn clean install

EXPOSE 8080

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.arguments=--server.address=0.0.0.0"]
