version: '1'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./:/app
    stdin_open: true
    tty: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
    stdin_open: true
    tty: true
